services:
  postgres-golang-rest-api:
    env_file: ".env"
    image: postgres:14.10
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-golang-rest-api-14-7:/var/lib/postgresql/data/
volumes:
  postgres-golang-rest-api-14-7:
